# Generated by Django 5.0.1 on 2024-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenca_medica',
            name='ciclo',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='licenca_medica',
            name='crm',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='licenca_medica',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenca_medica',
            name='responsavel',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
