# Generated by Django 5.0.1 on 2024-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercurso',
            name='certificado',
            field=models.CharField(blank=True, default=''),
        ),
    ]
