# Generated by Django 5.0.1 on 2024-01-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_cargo_alter_user_efetivacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
