# Generated by Django 5.0.1 on 2024-01-22 18:30

from django.db import migrations
from _core.data.funcionarios import funcionarios


def create_default_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Especialidade = apps.get_model('especialidades', 'Especialidade')
    Licenca_medica = apps.get_model('licencas_medicas', 'Licenca_medica')

    for entry in funcionarios:
        especialidades = entry.pop("especialidades")
        licenca_data = entry.pop("licenca_medica")
        licenca_medica = Licenca_medica(**licenca_data)
        licenca_medica.save()
        user = User.objects.create_superuser(
            **entry, licenca_medica=licenca_medica
        )

        for especialidade in especialidades:
            if especialidade == "-":
                ...
            else:
                saved_especialidade = Especialidade.objects.filter(
                    nome=especialidade
                ).first()
                if saved_especialidade:
                    user.especialidades.add(saved_especialidade)
                else:
                    new_especialidade = Especialidade.objects.create(
                        nome=especialidade
                    )
                    user.especialidades.add(new_especialidade)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ativo'),
    ]

    operations = [
        migrations.RunPython(create_default_data),
    ]
