# Generated by Django 5.0.1 on 2024-01-22 22:42

from django.db import migrations
from _core.data.registros import registros
from datetime import datetime


def create_default_data(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Registro_de_ponto = apps.get_model(
        'registros_de_ponto', 'Registro_de_ponto'
    )

    def getDateTime(date_str, time_str):
        dt_date = date_str.date()
        tm = datetime.strptime(time_str, '%H:%M:%S').time()

        return f"{dt_date} {tm}"

    for entry in registros:
        username = entry.pop("passaporte")
        user = User.objects.filter(username=username).first()
        if user:
            registro = {
                "entrada": getDateTime(entry['inicio'], entry['entrada']),
                "saida": getDateTime(entry['termino'], entry['saida']),
                "horas": f"{entry['horas']}",
                "user": user,
            }
            Registro_de_ponto.objects.create(**registro)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_migration_from_excel'),
    ]

    operations = [
        migrations.RunPython(create_default_data),
    ]
