# Generated by Django 5.0.1 on 2024-04-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_validade'),
        ('user_curso', '0001_initial'),
        ('users', '0005_remove_user_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cursos',
            field=models.ManyToManyField(related_name='users', through='user_curso.UserCurso', to='cursos.curso'),
        ),
    ]
