# Generated by Django 5.0.1 on 2024-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='validade',
            field=models.IntegerField(default=0),
        ),
    ]
