# Generated by Django 5.0.1 on 2024-01-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_de_ponto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_de_ponto',
            name='justificativa',
            field=models.TextField(blank=True),
        ),
    ]
